### ISSUE TITLE
[META][UI-CORE] Use Sass Loops for Border Styles

### ISSUE THREAD

**Issue by kmer2016** [osrd-project/osrd-ui#47]
This meta-issue suggests using Sass loops to manage border styles. It includes two main steps: creating Sass loops to generate border styles and using those loops throughout the project to ensure consistency and reduce redundant code.

- [ ] Create Sass loops for border styles
- [ ] Use the sass loops in the project
- [ ] Make sure the changes are well-documented
