### ISSUE TITLE
[META][UI-CORE] Setup for Visual Testing with Tailwind and Storybook

### ISSUE THREAD

**Issue by kmer2016** [osrd-project/osrd-ui#49]
setting up a configuration for visual testing in the project, using Tailwind for styling and Storybook for component visualization.

- [ ] Setup test configuration
- [ ] implement tests for components
   - [ ] Input
   - [ ] checkbox
   - [ ] select
   - [ ] textatrea
   - [ ] radio button
   - [ ] button
- [ ] start these tests in CI/CD pipeline
